package srvs

import (
	"encoding/gob"
	"encoding/json"
	"fmt"
	"os"
	"path"

	"github.com/wangkuiyi/fs"
	"github.com/wangkuiyi/phoenix/algo"
	"github.com/wangkuiyi/sego"
)

func GuaranteeSegmenter(sgmt **sego.Segmenter, dictFile string) error {
	if *sgmt == nil {
		s := new(sego.Segmenter)
		if e := s.LoadDictionary(dictFile); e != nil {
			return e
		}
		*sgmt = s
	}
	return nil
}

func GuaranteeVocabSharder(vocab **algo.Vocab, vshdr **algo.VSharder, tokensFile string, vshards int) error {
	if *vocab == nil || *vshdr == nil {
		tokens, e := fs.Open(tokensFile)
		if e != nil {
			return fmt.Errorf("GuaranteeVocabSharder failed to open %s: %v", tokensFile, e)
		}
		defer tokens.Close()

		v, s, e := algo.BuildVocabAndVSharder(tokens, vshards, true)
		if e != nil {
			return fmt.Errorf("GuaranteeVocabSharder(%s) failed: %v", tokensFile, e)
		}
		*vocab = v
		*vshdr = s
	}
	return nil
}

// GuaranteeConfig writes cfg into cfg.BaseDir/config if the file
// doesn't exist, or load from that file and overwrites cfg.  Anyway,
// GuaranteeConfig requires that cfg.BaseDir is set.
func GuaranteeConfig(cfg *Config) error {
	file := path.Join(cfg.BaseDir, "config")
	if _, e := fs.Stat(file); os.IsNotExist(e) {
		c, e := fs.Create(file)
		if e != nil {
			return fmt.Errorf("Failed to create config file %s: %v", file, e)
		}
		if e := json.NewEncoder(c).Encode(cfg); e != nil {
			return fmt.Errorf("Failed to encode config file %s: %v", file, e)
		}
		c.Close()
	} else {
		c, e := fs.Open(file)
		if e != nil {
			return fmt.Errorf("Failed to open config file %s: %v", file, e)
		}
		if e := json.NewDecoder(c).Decode(cfg); e != nil {
			return fmt.Errorf("Failed to decode config file %s: %v", file, e)
		}
		c.Close()
	}
	return nil
}

// GuaranteeModel loads a model vshard generated by the iter-th
// iteration from cfg.VShardPath(iter, vshard).  If iter < 0, it
// loads
func GuaranteeModel(model **algo.Model, vocab **algo.Vocab, vshdr **algo.VSharder, cfg *Config, arg *BootstrapArg) error {
	if *model == nil {
		if arg.Iter < 0 { // No existing model since initialziation is not yet completed.
			if e := GuaranteeVocabSharder(vocab, vshdr, cfg.Vocab, cfg.VShards); e != nil {
				return fmt.Errorf("GauranteeModel(%+v) failed: %v", arg, e)
			}
			*model = algo.NewModel(true, *vocab, *vshdr, arg.VShard, cfg.Topics)
		} else {
			f, e := fs.Open(cfg.VShardPath(arg.Iter, arg.VShard))
			if e != nil {
				return fmt.Errorf("GuaranteeModel(%+v) failed to open model vshard: %v", arg, e)
			}
			defer f.Close()

			*model = &algo.Model{}
			if e := gob.NewDecoder(f).Decode(*model); e != nil {
				return fmt.Errorf("GuarenteeModel(%+v) failed to decode model vshard: %v", arg, e)
			}
			*vocab = (*model).Vocab
			*vshdr = (*model).VShdr
		}
	}
	return nil
}
